name: Called regression tests
on:
  workflow_call:
    inputs:
      test_environment:
        type: string
        description: Against which env to run the tests test, local, acc
        required: true
      test_path:
        type: string
        description: Run specific suite
        default: tests
      test_tag:
        type: string
        description: Run test with specific Tag
        default: ""
    secrets:
      user:
        required: true
      password:
        required: true


jobs:
  reusable_workflow_job:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: 3.13.5

      - name: Setup Workspace
        working-directory: regression-tests
        run: |
          python -m pip install --upgrade pip poetry
          poetry install
          poetry run rfbrowser init

      - name: Run Chrome Tests against Environment
        working-directory: regression-tests
        run: |
            touch .env
            echo "HTACCESS_USER=${{ secrets.user }}" >> .env
            echo "HTACCESS_PASSWORD=${{ secrets.password }}" >> .env
            echo "ENVIRONMENT=${{ inputs.test_environment }}" >> .env
          
            export ENVIRONMENT=${{ inputs.test_environment }}
            poetry run robot \
            --removekeywords tag:secrets \
            --loglevel TRACE:INFO \
            --outputdir=./results \
            -v BROWSER:chromium \
            -v USER:${{ secrets.user }} \
            -v PASSWORD:${{ secrets.password }} \
            -v ENVIRONMENT:${{ inputs.test_environment }} \
            -i "${{ inputs.test_tag }}" \
            ${{ inputs.test_path }}/*
          
            poetry run rebot \
              --removekeywords tag:secrets \
              --output results/final_output.xml \
              results/output.xml
            mv results/final_output.xml results/output.xml

      - name: Upload Test Report Chrome
        uses: actions/upload-artifact@v4.3.1
        if: ${{ always() }}
        with:
          name: regression-tests-results-chrome-${{ inputs.test_environment }}
          path: regression-tests/results/

      - name: Publish Chrome results summary to GitHub
        uses: minvws/nl-rdo-github-action-robotframework-test-summary@0.4.3
        if: always()
        with:
          output_file: 'regression-tests/results/output.xml'
