name: Called regression tests
on:
  workflow_call:
    inputs:
      test_environment:
        type: string
        description: Against which env to run the tests test, local
        required: true
      test_path:
        type: string
        description: Run specific suite
        default: regression-tests/tests
      test_tag:
        type: string
        description: Run test with specific Tag
        default: ""
    secrets:
      user:
        required: true
      password:
        required: true


jobs:
  reusable_workflow_job:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: 3.12.6

      - name: Setup Workspace
        run: |
          sudo npx playwright install-deps
          python -m pip install --upgrade pip
          pip install -r regression-tests/requirements.txt
          rfbrowser init

      - name: Run Chrome Tests on Test
        run: |
          cd regression-tests
          export environment=${{ inputs.test_environment }}
          robot --removekeywords name:Setup --removekeywords tag:secrets --loglevel TRACE:INFO --outputdir=./results -v USER:${{secrets.user}} -v PASSWORD:${{secrets.password}} -v BROWSER:chromium -i ${{ inputs.test_tag }} -e local tests/*
          rebot --removekeywords tag:secrets --output results/final_output.xml results/output.xml
          mv results/final_output.xml results/output.xml

      - name: Upload Test Report Chrome
        uses: actions/upload-artifact@v4.3.1
        if: ${{ always() }}
        with:
          name: regression-tests-results-chrome
          path: regression-tests/results/

      - name: Publish Chrome results summary to GitHub
        uses: minvws/nl-rdo-github-action-robotframework-test-summary@v0.4.1
        if: always()
        with:
          output_file: 'regression-tests/results/output.xml'
