name: Local regression testing
on:
  workflow_dispatch:
  schedule:
    - cron: "15 4 * * *"
  push:
    branches:
      - main
      - develop
    paths:
      - 'regression-tests/**'
      - 'integration/**'
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.REPO_READ_ONLY_TOKEN }}

      - name: NPM configuration
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.REPO_READ_ONLY_TOKEN }}" > ~/.npmrc
          
      - name: Prepare docker-results directory
        run: |
          mkdir -p docker-results
          sudo chmod -R 777 docker-results
        working-directory: regression-tests

      - name: Build application
        run: |
          make NEW_GID=$(id -g) NEW_UID=$(id -u) BUILD_PROGRESS=plain build
        working-directory: integration

      - name: Run application
        env:
          HTACCESS_USER: ${{secrets.HTACCESS_USER}}
          HTACCESS_PASSWORD: ${{secrets.HTACCESS_PASSWORD}}
        run: make start
        working-directory: integration

      - name: Run Robot Framework Tests
        env:
          HTACCESS_USER: ${{secrets.HTACCESS_USER}}
          HTACCESS_PASSWORD: ${{secrets.HTACCESS_PASSWORD}}
          ENVIRONMENT: local
        run: ./runtests-in-docker.sh
        working-directory: regression-tests

      - name: Collect Docker Logs on Failure
        if: failure() && endsWith(github.repository, '-private')
        run: docker compose logs --timestamps
        working-directory: integration
          
      - name: Test Results on Integration
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: regression-tests/docker-results/

      - name: Publish Chrome results summary to GitHub
        uses: minvws/nl-rdo-github-action-robotframework-test-summary@0.4.3
        if: always()
        with:
          output_file: 'regression-tests/docker-results/output.xml'